### PR TITLE
feat: send notification to resource author on hide instead of on report

### PR DESCRIPTION
**Pull request by orlera**
#### :tophat: What? Why?
https://github.com/decidim/decidim/pull/6747 introduced sending a notification to the authors when their content gets reported.
Now we want to send the notification when the reported content is hidden (removed) by a moderator instead of when it has been reported.

The notification/email will report to the author(s) the reason(s) why their content was reported to the moderators.

#### :pushpin: Related Issues
- Related to https://github.com/decidim/decidim/pull/6747

#### Testing
Login with a user (say: user@example.org | decidim123456);
Create a reportable content (e.g. a comment, proposal, etc.);
On another browser/session, login with another user (say: admin@example.org | decidim123456);
Report the content created with the previous user;
As an admin (say: admin@example.org | decidim123456), navigate to the process' moderation panel and 'hide' the moderation created in the previous step;
The first user (user@example.org in the example) shell receive a notification saying that their content has been removed;

#### :clipboard: Checklist
:rotating_light: Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [ ] :question: **CONSIDER** adding a unit test if your PR resolves an issue.
- [ ] :heavy_check_mark: **DO** check open PR's to avoid duplicates.
- [ ] :heavy_check_mark: **DO** keep pull requests small so they can be easily reviewed.
- [ ] :heavy_check_mark: **DO** build locally before pushing.
- [ ] :heavy_check_mark: **DO** make sure tests pass.
- [ ] :heavy_check_mark: **DO** make sure any new changes are documented in `docs/`.
- [ ] :heavy_check_mark: **DO** add and modify seeds if necessary.
- [ ] :heavy_check_mark: **DO** add CHANGELOG upgrade notes if required.
- [ ] :heavy_check_mark: **DO** add to GraphQL API if there are new public fields.
- [ ] :heavy_check_mark: **DO** add link to MetaDecidim if it's a new feature.
- [ ] :x:**AVOID** breaking the continuous integration build.
- [ ] :x:**AVOID** making significant changes to the overall architecture.

### :camera: Screenshots
Notification
notification

Email
email

:hearts: Thank you!

### CODE REVIEW

**Comment by orlera** [comment]
@mrcasals removed the dead link and added a summary of the hidden resource

**Comment by mrcasals** [comment]
@orlera there's some issues with the Lin, can you check it? Also, can you paste a screenshot of the email, if possible? Thanks! :)

**Comment by orlera** [comment]
@mrcasals yup, sorry about that! Checks should pass now 🤞

**Comment by mrcasals** [comment]
Awesome, thanks!

**Review by mrcasals — APPROVED** [review]

**Comment by orlera** [comment]
After an iteration with the client, it was decided to change the order of the filters in the dashboard
image

**Pull request merged**
